# Generated by Django 5.2.7 on 2025-11-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
