# Generated by Django 5.2.7 on 2025-11-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_post_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
