# Generated by Django 5.2.7 on 2025-11-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_division_alter_order_payment_method_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
